@Bloggy_Api_HostAddress = http://localhost:5010

### Register
POST {{Bloggy_Api_HostAddress}}/api/v1/oauth/register
Accept: application/json
Content-Type: application/json

{
    "username": "Cyril",
    "email": "cyril@mail.com",
    "password": "c12345678"
}

### Login
POST {{Bloggy_Api_HostAddress}}/api/v1/oauth/login
Accept: application/json
Content-Type: application/json

{
    "email": "cyril@mail.com",
    "password": "c12345678"
}

### Refresh
POST {{Bloggy_Api_HostAddress}}/api/v1/oauth/refresh
Accept: application/json

### Logout
POST {{Bloggy_Api_HostAddress}}/api/v1/oauth/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZDE4YmQ4MC0yNjE1LTQ0NjctYmNiOC03MTk2ZjFkMmE0ZGUiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiNmIyYmJlNjQtNzJmOS00ZGQxLThkMDMtYWRmMmJmOThkNjI0IiwiZXhwIjoxNzAyMjE3MjkzLCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9._dcfuNIk31D4JGV6wdgR0Flp_XG1UoZXE6OGlnNlk3E

### Get by id
GET {{Bloggy_Api_HostAddress}}/api/v1/accounts/c116ecf1-73bc-49ef-b1d1-7f36eb2d5df0
Accept: application/json

### My
GET {{Bloggy_Api_HostAddress}}/api/v1/accounts/my
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYmRjOTNlNS01ZGNlLTQzNDUtYThmOC1mYTM4NDMyY2FmZjgiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiY2M5MjljZWMtNjZjZi00YjI0LWIxMTgtZTEzZjIxNDA2OWUyIiwiZXhwIjoxNzAyMTQxNzQxLCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.3szqoBYa-phB3icECJffsb8JzKAWLRCfrIM2QxSVa5s
Content-Type: application/json

### Change password
PUT {{Bloggy_Api_HostAddress}}/api/v1/accounts/change-password
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwM2I5NTc3OC0xYWJjLTQxZjEtOTY5My1hNjUyYmM0NGE1OWYiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiOGE3ZDM2MzYtODQ3MS00ODMxLTllNzQtMjRlMjg1NDFjYTY3IiwiZXhwIjoxNzAxOTQ3NTk4LCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.vHjLDezM8NurNSLq_95GHUsxBSdGZI10erlkAw6vVYw
Content-Type: application/json

{
    "oldPassword": "c12345678",
    "newPassword": "cyril123"
}

### Delete
DELETE {{Bloggy_Api_HostAddress}}/api/v1/accounts/my
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNmJiNTg1Mi0wOTE0LTQ0N2ItOWQwNC0wYjQ1OTFhYmQzMTAiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiOTlhNzhjZDEtYjQ4MS00NTU1LTgxMDgtOTY1ZWMyZmM1ZGRlIiwiZXhwIjoxNzAxOTQ4MjY2LCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.Plo7OL4NKsETDHxgQYt8yplvH3barg3ECPhKPZwTuBQ

### Upload image to user profile
POST {{Bloggy_Api_HostAddress}}/api/v1/accounts/my/image
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYTJmYTU1Yy00ZGVkLTQ5MTEtOGI1Yi0zYjQyMTgwYzFiMzMiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiYWUwOGY0MTQtYzQwMS00YjQxLTlmM2QtNzZlZjAzNmY5ZjFlIiwiZXhwIjoxNzAxOTUzMDczLCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.pRdLT8krE0_tMXzoBV3w_PcaZIp7JwEfuPcRKU79Hyw
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="Image"; filename="logo.png"
Content-Type: image/png

< C:\Users\kiril\Downloads\logo.png
--MfnBoundry--

### Delete image
DELETE {{Bloggy_Api_HostAddress}}/api/v1/accounts/my/image
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYTJmYTU1Yy00ZGVkLTQ5MTEtOGI1Yi0zYjQyMTgwYzFiMzMiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiYWUwOGY0MTQtYzQwMS00YjQxLTlmM2QtNzZlZjAzNmY5ZjFlIiwiZXhwIjoxNzAxOTUzMDczLCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.pRdLT8krE0_tMXzoBV3w_PcaZIp7JwEfuPcRKU79Hyw

### Get image
GET {{Bloggy_Api_HostAddress}}/images/user_image_0a2fa55c-4ded-4911-8b5b-3b42180c1b33.png
Accept: application/json

### Get all topics
GET {{Bloggy_Api_HostAddress}}/api/v1/topics/
Accept: application/json

### Create new post
POST {{Bloggy_Api_HostAddress}}/api/v1/posts/
Accept: : application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOWNhZDI2MS1kZWZhLTRiNGYtYjM5Yi0wZmNhNDlmYmQ1ODMiLCJuYW1lIjoiQ3lyaWwiLCJlbWFpbCI6ImN5cmlsQG1haWwuY29tIiwianRpIjoiNzE5MWQ5YWUtOTJkMi00MmFkLTllMWQtNGIwODAzMGQ4ZGE1IiwiZXhwIjoxNzAyNTY1MDE5LCJpc3MiOiJCbG9nZ3kuY29tIiwiYXVkIjoiQmxvZ2d5LmNvbSJ9.Ke9hMNWiCpWXkibCdKxhNrhJq_I1OcXvza5EP4PeqYk

{
    "title": "Post 1",
    "description": "...",
    "topics": [1,2,3]
}

### Get all posts
GET {{Bloggy_Api_HostAddress}}/api/v1/posts/
Accept: : application/json